// Editable skill↔role table for the officer optimizer, transcribed from doc/officer-skills.md.
// Keyed by the skill's DISPLAY NAME (matches the `name` field the bridge returns per skill node).
// `roles` = the professions/roles the skill belongs to (used for the optimizer's role-relevance
// tiebreak). `drone` = the skill only counts when the ship has a drone bay. `major` = the powerful
// single-slot skill (vs a stacking minor). `effect` = short human description for the UI.
export interface SkillMeta {
  roles: string[];      // any of: Combat, Mining, Salvaging, Engineering, Industrial, Unique
  drone?: boolean;      // marked [drone] in the doc
  major?: boolean;      // "(major)" in the doc; minors omit this
  effect?: string;      // e.g. "Attack Speed +12%"
}

export const OFFICER_SKILLS: Record<string, SkillMeta> = {
  "Annihilator": { roles: ["Combat", "Engineering", "Unique"], effect: "Crit Damage +5%" },
  "Armor Leech": { roles: ["Engineering", "Industrial"], effect: "dmg → armor +0.5%" },
  "Armor Plating": { roles: ["Engineering"], major: true, effect: "Armor HP +10%" },
  "Armor Repair Bot": { roles: ["Mining", "Engineering"], effect: "repair bots restore 1% armor/2s" },
  "Assault Doctrine": { roles: ["Combat", "Engineering"], effect: "Boarding Power +10%" },
  "Clean Sweep": { roles: ["Salvaging"], major: true, effect: "wreck kill → Salvage Power +20% (2min)" },
  "Composite Drone Armor": { roles: ["Combat"], drone: true, effect: "Drone Damage Reduction +3%" },
  "Crew Conditioning": { roles: ["Engineering"], effect: "Crew Resistance +10%" },
  "Critical Recursion": { roles: ["Combat"], effect: "crit retrigger" },
  "Drone": { roles: ["Engineering", "Unique"], drone: true, major: true, effect: "Drone Power +2.5%, drone Attack Speed +5%" },
  "Drone Agility": { roles: ["Combat", "Mining", "Salvaging"], drone: true, effect: "Drone Engine Thrust +10%" },
  "Drone Handler": { roles: ["Combat", "Engineering"], drone: true, major: true, effect: "Drone Power +5%" },
  "ECHO The Conqueror": { roles: ["Engineering", "Industrial"], effect: "idle conquest → Fleet Strength +20%" },
  "Efficient Miner": { roles: ["Mining"], major: true, effect: "Mining Power +5%" },
  "Enhanced Beams": { roles: ["Salvaging"], effect: "Salvage Power +1% (min +3)" },
  "Equipment Bonus": { roles: ["Mining"], effect: "equipment extraction +10%/rank" },
  "Excavation Actuators": { roles: ["Combat", "Mining", "Salvaging", "Engineering", "Industrial"], effect: "Turret Rotation Speed +4%" },
  "Experience Penalty Reducer": { roles: ["Engineering"], effect: "XP penalty -2%" },
  "Extended Brig": { roles: ["Engineering"], effect: "Brig +10%" },
  "Fault Line": { roles: ["Mining"], major: true, effect: "crit asteroid → Yield +10% (8s)" },
  "Faster Production I": { roles: ["Engineering", "Industrial"], effect: "refinery/forge +8%" },
  "Faster Production II": { roles: ["Engineering", "Industrial"], effect: "refinery/forge +15%" },
  "Field Focus": { roles: ["Mining", "Unique"], major: true, effect: "asteroid arrival → Mining Power +12.5% (60s)" },
  "Fieldwork Power Efficiency": { roles: ["Engineering"], effect: "Mining/Salvage power penalty -2%" },
  "Fire Control Officer": { roles: ["Combat"], major: true, effect: "Attack Speed +12%" },
  "From Memory": { roles: ["Unique"], effect: "Warp travel speed +5%" },
  "Harvester": { roles: ["Mining", "Salvaging", "Industrial"], major: true, effect: "Yield +2.5%" },
  "Hazard Leech": { roles: ["Mining", "Salvaging", "Engineering", "Industrial"], effect: "25% hazard dmg → Yield +5%" },
  "Hidden Crystals": { roles: ["Engineering", "Industrial"], effect: "0.3% ore refine → crystal" },
  "Instant Reload": { roles: ["Combat"], effect: "2% instant reload" },
  "Iron Rage": { roles: ["Combat", "Unique"], major: true, effect: "hull dmg → +25% Combat Power (10s cd)" },
  "Loadmaster": { roles: ["Mining", "Salvaging", "Engineering", "Industrial"], major: true, effect: "Cargo Capacity +5%" },
  "Lode Sense": { roles: ["Mining"], major: true, effect: "5% ore upgrades tier" },
  "Lucky Haul": { roles: ["Salvaging"], major: true, effect: "1% salvage hit drops wreck item" },
  "Miner's Edge": { roles: ["Mining"], effect: "Mining Power +1% (min +3)" },
  "Optimized Drone Tools": { roles: ["Combat"], drone: true, effect: "Drone Power +2%" },
  "Ore Hold Retrofit": { roles: ["Mining", "Industrial"], effect: "Cargo Capacity +30" },
  "Overwhelming Resolve": { roles: ["Engineering", "Industrial"], effect: "Damage Reduction +2% (3+ enemies)" },
  "Power Tools": { roles: ["Engineering", "Industrial", "Unique"], drone: true, effect: "Drone Power +1%" },
  "Precise Targeting": { roles: ["Combat"], effect: "Crit Chance +1%" },
  "Precision Module": { roles: ["Mining"], effect: "Mining Power +1%, Yield +1%" },
  "Precision Scraping": { roles: ["Salvaging"], effect: "Yield +2%" },
  "Quick Rebuild": { roles: ["Engineering", "Industrial"], drone: true, effect: "Drone rebuild -7.5%" },
  "Range Amplifier": { roles: ["Combat", "Mining", "Salvaging", "Engineering"], effect: "Turret Range +5%" },
  "Rapid Assault": { roles: ["Combat"], effect: "Attack Speed +3%" },
  "Rapid Deployment": { roles: ["Engineering", "Industrial", "Unique"], drone: true, effect: "Drone deployment +40%" },
  "Reactor Rest": { roles: ["Mining"], major: true, effect: "reactor energy -50% 30s after asteroid hit" },
  "Reactor Technician": { roles: ["Combat"], major: true, effect: "Energy Capacity +10%" },
  "Redline": { roles: ["Combat"], effect: "crit → Rage stacks (+0.5% Combat Power/stack)" },
  "Resource Maximizer": { roles: ["Mining", "Engineering"], effect: "Yield +2%" },
  "Salvage Racks": { roles: ["Salvaging"], effect: "Cargo Capacity +25" },
  "Salvage Surge": { roles: ["Salvaging"], major: true, effect: "salvage arrival → Salvage Power +12.5% (60s)" },
  "Scavenger": { roles: ["Salvaging"], major: true, effect: "Salvage Power +5%" },
  "Sharp Eye": { roles: ["Salvaging"], major: true, effect: "crit wreck → Yield +5% (5x)" },
  "Shield Boost": { roles: ["Engineering"], major: true, effect: "Shield HP +10%" },
  "Shield Leech": { roles: ["Engineering", "Industrial"], effect: "dmg → shields +0.5%" },
  "Shock Assault": { roles: ["Combat"], major: true, effect: "enemy Boarding Power -5% while boarding" },
  "Smart Extraction": { roles: ["Engineering"], effect: "Mining/Salvage yield penalty -2%" },
  "Smugglers Stash": { roles: ["Mining"], effect: "1% locked container in asteroid" },
  "Strip Focus": { roles: ["Salvaging"], major: true, effect: "salvage hits → Salvage Power +5% (5x)" },
  "Sustained Operator": { roles: ["Engineering"], major: true, effect: "autopilot use → efficiency +1% (max 10%)" },
  "System Optimizer": { roles: ["Engineering"], major: true, effect: "autopilot delay -0.5s" },
  "Target Weak Spots": { roles: ["Combat"], effect: "Crit Chance +1%, Crit Damage +2.5%" },
  "Targeting Specialist": { roles: ["Combat"], major: true, effect: "Crit Chance +2%, Crit Damage +5%" },
  "Turret Rotation": { roles: ["Combat", "Mining", "Salvaging", "Engineering", "Industrial"], effect: "Turret Rotation Speed +5%" },
  "Veteran's Might": { roles: ["Combat"], effect: "Combat Power +1% (min +3)" },
  "Warpath": { roles: ["Combat"], major: true, effect: "kills → Attack Speed stacks" },
  "Weapons Free": { roles: ["Combat"], major: true, effect: "combat arrival → Attack Speed +10%" },
};
